openapi: 3.0.1
info:
  title: StoreSamadhan
  description: Store Samadhan App
  version: 1.0.0
servers:
  - url: /api/v1

tags:
  - name: Auth
    description: Authentication endpoints
  - name: User
    description: User endpoints

paths:
  /auth/getUserDetails:
    get:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Get user details
      description: Get user details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserDetailsResponse"
  /auth/signupUser:
    post:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Signup a new user
      description: Signup a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupUser"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /auth/signupStorage:
    post:
      tags:
        - Auth
      security:
        - Bearer: []
      summary: Signup a new storage
      description: Signup a new storage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupStorage"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /user/bookings:
    get:
      tags:
        - User
      security:
        - Bearer: []
      summary: Get user bookings
      description: Get user bookings
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserBookingsResponse"
  /user/updateUser:
    put:
      tags:
        - User
      security:
        - Bearer: []
      summary: Update user
      description: Update user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUser"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /user/addRating:
    post:
      tags:
        - User
      security:
        - Bearer: []
      summary: Add rating
      description: Add rating
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddRating"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Provide a valid JWT token
  schemas:
    GetUserDetailsResponse:
      type: object
      properties:
        email:
          type: string
        createdAt:
          type: object
          properties:
            _seconds:
              type: number
            _nanoseconds:
              type: number
        city:
          type: string
        state:
          type: string
        phone:
          type: number
        name:
          type: string
        profilePicture:
          type: string
    SignupUser:
      type: object
      required:
        - name
        - email
        - state
        - city
      properties:
        name:
          type: string
        phone:
          type: number
        email:
          type: string
        state:
          type: string
        city:
          type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    SignupStorage:
      type: object
      required:
        - name
        - email
        - address
        - location
        - state
        - city
        - pincode
      properties:
        name:
          type: string
        phone:
          type: number
        email:
          type: string
        address:
          type: string
        location:
          type: string
        state:
          type: string
        city:
          type: string
        pincode:
          type: number
    UpdateUser:
      type: object
      properties:
        userData:
          type: object
          properties:
            name:
              type: string
            phone:
              type: number
            email:
              type: string
            addresses:
              type: array
              items:
                type: object
                properties:
                  address:
                    type: string
                  pincode:
                    type: number
            state:
              type: string
            city:
              type: string
    AddRating:
      type: object
      properties:
        rating:
          type: number
        storageId:
          type: string
        review:
          type: string
    GetUserBookingsResponse:
      type: object
      properties:
        bookings:
          type: array
          items:
            type: object
            properties:
              storageId:
                type: string
              storageName:
                type: string
              address:
                type: string
              image:
                type: string
              fromDate:
                type: object
                properties:
                  _seconds:
                    type: number
                  _nanoseconds:
                    type: number
              toDate:
                type: object
                properties:
                  _seconds:
                    type: number
                  _nanoseconds:
                    type: number
              paid:
                type: boolean
              amount:
                type: number
              boxes:
                type: number
              orderId:
                type: string
